#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pycountry
Version  : 20.7.3
Release  : 1
URL      : https://files.pythonhosted.org/packages/76/73/6f1a412f14f68c273feea29a6ea9b9f1e268177d32e0e69ad6790d306312/pycountry-20.7.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/76/73/6f1a412f14f68c273feea29a6ea9b9f1e268177d32e0e69ad6790d306312/pycountry-20.7.3.tar.gz
Summary  : ISO country, subdivision, language, currency and script definitions and their translations
Group    : Development/Tools
License  : LGPL-2.1
Requires: pypi-pycountry-license = %{version}-%{release}
Requires: pypi-pycountry-python = %{version}-%{release}
Requires: pypi-pycountry-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
=========

%package license
Summary: license components for the pypi-pycountry package.
Group: Default

%description license
license components for the pypi-pycountry package.


%package python
Summary: python components for the pypi-pycountry package.
Group: Default
Requires: pypi-pycountry-python3 = %{version}-%{release}

%description python
python components for the pypi-pycountry package.


%package python3
Summary: python3 components for the pypi-pycountry package.
Group: Default
Requires: python3-core
Provides: pypi(pycountry)

%description python3
python3 components for the pypi-pycountry package.


%prep
%setup -q -n pycountry-20.7.3
cd %{_builddir}/pycountry-20.7.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639055108
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pycountry
cp %{_builddir}/pycountry-20.7.3/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-pycountry/d107038f94edcd860227cc8d3c96c495243e8ee6
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pycountry/d107038f94edcd860227cc8d3c96c495243e8ee6

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
